export const FETCH_INGREDIENTS = "FETCH_INGREDIENTS"

export const FETCH_USER_INGREDIENTS = "FETCH_USER_INGREDIENTS"

export const ADD_USER_INGREDIENT = "ADD_USER_INGREDIENT"

export const DELETE_USER_INGREDIENT = "DELETE_USER_INGREDIENT"

export const FETCH_COCKTAILS = "FETCH_COCKTAILS"

export const FETCH_SHOPPING_LIST = "FETCH_SHOPPING_LIST"

export const ADD_TO_SHOPPING_LIST = "ADD_TO_SHOPPING_LIST"

export const DELETE_LIST_ITEM = "DELETE_LIST_ITEM"

export const CREATE_USER = "CREATE_USER"

export const LOGIN_USER = "LOGIN_USER"

export const SAVE_COCKTAIL = "SAVE_COCKTAIL"

export const FETCH_SAVED_COCKTAILS = "FETCH_SAVED_COCKTAILS"

export const ADD_NOTE_TO_SAVED_COCKTAIL = "ADD_NOTE_TO_SAVED_COCKTAIL"