export const FETCH_INGREDIENTS = "FETCH_INGREDIENTS"

export const FETCH_USER_INGREDIENTS = "FETCH_USER_INGREDIENTS"

export const ADD_USER_INGREDIENT = "ADD_USER_INGREDIENT"

export const DELETE_USER_INGREDIENT = "DELETE_USER_INGREDIENT"

export const FETCH_COCKTAILS = "FETCH_COCKTAILS"